### ISSUE TITLE
Ortholinks broken

### ISSUE THREAD

**Issue by yingzhu146** [lhm30/PIDGINv3#6]
Thank you for great package!

Links for zip files are broken, like https://universityofcambridgecloud-my.sharepoint.com/:u:/g/personal/lhm30_cam_ac_uk/EfapgV8syj1Hn0fv8we5wFABxKdCbETXt_zigDc0XkMI9g?e=rcxogX shows:

This link has been disabled.

Any help?

Thank you!

**Comment by lewismervin1** [comment]
We are working on getting the links back up and running. 
Hosting such large files is posing issues.
Thanks for your patience.

**Comment by yingzhu146** [comment]
Other such as DeepChem using S3 bucket - maybe help here too?

**Comment by lhm30** [comment]
Links are fixed
